Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                           0.51                           0.75
  y                          -0.47                          -0.60
  z                          -0.20                           0.75
abs                           0.72                           1.21
                    unit:  μC/cm2                 unit:  μC/cm2
